site_name: Cadwork Documentation

repo_name: cwdocs/cwdocs
repo_url: https://github.com/cwdocs/cwdocs
edit_uri: ""

copyright: Copyright &copy; 2025 Cadwork

site_url: https://docs.cadwork.com/

theme:
  name: material
  logo: cw_logo.svg
  favicon: cw_logo.svg
  version: V2025
  features:
    - search.suggest
    - search.highlight

markdown_extensions:
  - attr_list  
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences:
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: cwdocs
      repo: cwdocs

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      separator: '[\s\-\.\_]+'     
  - mkdocstrings

plugins:
  - search:
      separator: '[\s\-\.\_]+'  
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - build: true
          default: false
          locale: de
          name: Deutsch
        - build: true
          default: true
          locale: en
          name: English
        - build: true
          default: false
          locale: fr
          name: Français
      reconfigure_material: true
      reconfigure_search: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cwdocs
      name: CWDOCS
